# This file was generated by GoReleaser. DO NOT EDIT.
cask "cadence" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "0590de3b2dfe5d620cb890916632d8f6e0bfd76587087d494704ebc43fff99b8"
      url "https://github.com/rizwanreza/cadence-cli/releases/download/v#{version}/cadence_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "34b8ccc7b26d2e052f3f213b85d9794f07f9db27a51bcef53de8d63ebe36d98a"
      url "https://github.com/rizwanreza/cadence-cli/releases/download/v#{version}/cadence_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fed771cee37019e46eaaa16aeb51b689c342cdfedd855ff83677b6e81156d87c"
      url "https://github.com/rizwanreza/cadence-cli/releases/download/v#{version}/cadence_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f5c843b8ad44c6dd184df8096ed8949d0c2e8278e1fb16f30ec6fe8592100a4e"
      url "https://github.com/rizwanreza/cadence-cli/releases/download/v#{version}/cadence_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cadence"
  desc "Run your 12-Week Year from the terminal, or let your agent do it"
  homepage "https://cadenceweek.com/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cadence"
  bash_completion "completions/cadence.bash"
  fish_completion "completions/cadence.fish"
  zsh_completion "completions/cadence.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cadence"]
    end
  end

  # No zap stanza required
end
