# This file was generated by GoReleaser. DO NOT EDIT.
cask "smartly" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "a5b27c48929a444f56bc2b37fe7ea106f9928cefaab783e25fbb2b73003374a6"
      url "https://github.com/rizwanreza/smartly-cli/releases/download/v#{version}/smartly_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e582c3810c1efd4672eb19d46d26e527cfb68b7f4394b2d97424bc1ce022cbb5"
      url "https://github.com/rizwanreza/smartly-cli/releases/download/v#{version}/smartly_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "20fb23079c81e4e543c71839fe2551572f18097619903b400977ce7b8e72354f"
      url "https://github.com/rizwanreza/smartly-cli/releases/download/v#{version}/smartly_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bc0df7c34a83d7f2d0b07688e68221456b58aff59c6f2f89579989d5d814bd48"
      url "https://github.com/rizwanreza/smartly-cli/releases/download/v#{version}/smartly_linux_amd64.tar.gz"
    end
  end

  name "smartly"
  desc "Turn an English sentence into an executable shell command"
  homepage "https://smartlycli.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "smartly"

  # No zap stanza required

  caveats <<~EOS
    Run `smartly config init` to write a default config, and
    `eval "$(smartly init bash)"` (or `init zsh`) in your shell rc file
    to enable commands that change directory or set environment variables.
  EOS
end
