# This file was generated by GoReleaser. DO NOT EDIT.
cask "smartly" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "03e2aaf440615598f41aa0dcc77c6ef4d7ab7d3100f7ebc3f6ea2a5c296b51f1"
      url "https://github.com/rizwanreza/smartly-cli/releases/download/v#{version}/smartly_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9e51b8ac967ce8042a74b4afb70a004c9eb338bfddb1196f4361f53991f9fb86"
      url "https://github.com/rizwanreza/smartly-cli/releases/download/v#{version}/smartly_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "51767f80e40ec6751af17e97e56bd7fc4410c72f2b019f96fc9e994fd958e53c"
      url "https://github.com/rizwanreza/smartly-cli/releases/download/v#{version}/smartly_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "67e9cebf528a9d1cfd0caae9e9207ee92686e7d2fc0b5ca018673a2ff3b29df2"
      url "https://github.com/rizwanreza/smartly-cli/releases/download/v#{version}/smartly_linux_arm64.tar.gz"
    end
  end

  name "smartly"
  desc "Turn an English sentence into an executable shell command"
  homepage "https://github.com/rizwanreza/smartly-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "smartly"

  # No zap stanza required

  caveats <<~EOS
    smartly's binaries are not yet signed with an Apple Developer ID. If
    you installed without --no-quarantine, macOS Gatekeeper will block the
    binary — do NOT click "Move to Trash"; instead run:

      xattr -d com.apple.quarantine "$(brew --prefix)/Caskroom/smartly/"*/smartly

    Run `smartly config init` to write a default config, and
    `eval "$(smartly init bash)"` (or `init zsh`) in your shell rc file
    to enable commands that change directory or set environment variables.
  EOS
end
