# This file was generated by GoReleaser. DO NOT EDIT.
cask "smartly" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "8b1569aafd6c17d451e8ca9b55bb27f40591141457e3ee72f6365845c24b4b1b"
      url "https://github.com/rizwanreza/smartly-cli/releases/download/v#{version}/smartly_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c281ebb5fd76e2e4c8d47b90cd1c0d93221771b5297b1a8c3564ec7e4843ad39"
      url "https://github.com/rizwanreza/smartly-cli/releases/download/v#{version}/smartly_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "74137064555cefc5f97ab05d31a54286a5e86b1bf0dfe80704b3e50c16f46e7b"
      url "https://github.com/rizwanreza/smartly-cli/releases/download/v#{version}/smartly_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a4260f653bad476788329ed6bb1963705a256947bbd6e5f4256324d30405302d"
      url "https://github.com/rizwanreza/smartly-cli/releases/download/v#{version}/smartly_linux_arm64.tar.gz"
    end
  end

  name "smartly"
  desc "Turn an English sentence into an executable shell command"
  homepage "https://github.com/rizwanreza/smartly-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "smartly"

  # No zap stanza required

  caveats <<~EOS
    Run `smartly config init` to write a default config, and
    `eval "$(smartly init bash)"` (or `init zsh`) in your shell rc file
    to enable commands that change directory or set environment variables.
  EOS
end
